import '../_temp-root.mjs'           // ★맨 앞 — 검사 도구가 임시 자리를 C 드라이브로 정하기 전에
import { _electron as electron } from 'playwright'
import fs from 'fs'
import path from 'path'
import os from 'os'
import { isolatedUserData, cleanupUserData, makeSyntheticWav } from './_e2e-helper.mjs'
const root=process.cwd(),ud=isolatedUserData(),src=makeSyntheticWav(path.join(ud,'reference-a.wav'),8),other=makeSyntheticWav(path.join(ud,'reference-b.wav'),7,24000,220)
const shots=fs.mkdtempSync(path.join(os.tmpdir(),'af-unified-cards-shots-'))
let app,win,passed=0;const errors=[]
const capture=async name=>{await win.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(shots,name+'.png'),Buffer.from(png,'base64'))};
const check=(v,label)=>{if(!v)throw Error(label);passed++;console.log('PASS',label)}
try{
 app=await electron.launch({args:['out/main/index.js'],cwd:root,env:{...process.env,AF_E2E:'1',AF_E2E_USER_DATA:ud,AUDIOFORGE_NO_WARMUP:'1',HF_HUB_OFFLINE:'1',AF_E2E_SELECT_FILE:src}})
 win=await app.firstWindow();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1280,850));win.setDefaultTimeout(10000);win.on('pageerror',e=>errors.push(e.message))
 await win.waitForFunction(()=>!!window.__afStore&&!!window.__synthesisCards)
 await app.evaluate(({ipcMain},src)=>{
  const replace=(c,f)=>{ipcMain.removeHandler(c);ipcMain.handle(c,f)}
  globalThis.__cardCalls=0;globalThis.__cardTrimCalls=0
  replace('audio:select-file',()=>src)
  replace('audio:get-file-info',(_e,p)=>({path:p,name:p.split(/[/\\]/).pop(),duration:8,sampleRate:24000,channels:1,format:'wav'}))
  replace('card:extract-audio',(_e,_id,p)=>({ok:true,data:p}))
  replace('audio:trim-reference',()=>{globalThis.__cardTrimCalls++;return {error:'GUI 검사: 구간 미확정'}})
  replace('audio:process',()=>{globalThis.__cardCalls++;throw Error('GUI-only should not synthesize')})
  replace('analysis:prewarm',()=>({ready:false}))
  replace('analysis:analyze',(_e,req)=>({ok:false,requestId:req.requestId,code:'WORKER_UNAVAILABLE',reason:'GUI check'}))
  replace('audio:analyze-reference',()=>({valid_whole:false,too_short:false,needs_region:true,duration_sec:8,sample_rate:24000,channels:1,policy:{engine:'qwen3',required:{min_sec:1,max_sec:null},recommended:{min_sec:3,max_sec:5}},recommend:{ok:false}}))
 },src)
 await win.getByTestId('mode-tts').click()
 await win.getByTestId('synthesis-card-workspace').waitFor()
 check(await win.getByTestId('synthesis-tabs').count()===0,'통합 화면에 제작 방식 탭 없음')
 check(await win.getByTestId('generation-card').count()===0,'초기에는 파일 없는 카드도 없음')
 check(await win.getByTestId('synthesis-empty-source').isVisible(),'빈 합성 화면에 파일 불러오기 카드 표시')
 check(await win.getByRole('button',{name:'합성할 목소리의 오디오 또는 영상 파일 선택'}).isVisible(),'파일 선택 목적을 이름으로 구분')
 const emptyBox=await win.getByRole('region',{name:'첫 목소리'}).boundingBox()
 check(emptyBox.width<=581,'빈 입력 카드가 화면 전체로 늘어나지 않음')
 await capture('00-empty-source')
 await win.getByRole('button',{name:'기본 목소리 선택',exact:true}).click()
 await win.getByRole('dialog',{name:'목소리 고르기'}).waitFor()
 // 새 목소리 고르기는 '기본 목소리' / '내 목소리 파일' 탭이다 — 기본 목소리 탭이 열리고, 파일 통로는 내 목소리 파일 탭에 있다(같은 통로를 새 조작으로 본다).
 check(await win.getByTestId('voice-source-builtin').isVisible(),'기본 목소리 통로 유지')
 await win.getByTestId('voice-source-reference').click()
 check(await win.getByTestId('pick-voice-file').isVisible(),'기본 목소리 선택 통로 유지(내 목소리 파일 탭)')
 await win.keyboard.press('Escape')

 await win.evaluate(p=>window.__afStore.setState({fileInfo:{path:p,name:'목소리 A.wav',duration:8,channels:1,sampleRate:24000,format:'wav'}}),src)
 await win.getByTestId('generation-card').waitFor()
 await win.waitForFunction(()=>document.querySelector('[data-testid="compact-voice-wave"]')?.dataset.state==='ready')
 check(await win.getByTestId('generation-card').count()===1,'공통 원본으로 첫 카드 자동 구성')
 await win.getByTestId('card-reference-review').first().click()
 check(await win.getByRole('combobox',{name:'참조 구간 방식'}).isVisible(),'구간 확인에서 참조 설정을 바로 펼침')
 check(await win.getByRole('combobox',{name:'참조 구간 방식'}).evaluate(el=>el===document.activeElement),'구간 확인 후 참조 선택에 키보드 초점')
 await win.keyboard.press('Escape')
 await win.getByTestId('card-script').fill('안녕하세요. 오늘은 함께 이야기를 만들어 볼까요?')
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 await win.getByRole('dialog',{name:'고급 옵션'}).waitFor()
 check(await win.locator('dialog').evaluate(el=>el.contains(document.activeElement)),'팝업 내부로 키보드 초점 이동')
 await win.getByRole('slider',{name:'말하기 속도'}).fill('1.2')
 check(await win.getByRole('slider',{name:'음높이'}).getAttribute('max')==='2'&&await win.getByRole('slider',{name:'음높이'}).getAttribute('step')==='0.5','음높이 엔진 범위와 일치')
 check(await win.getByRole('combobox',{name:'감정',exact:true}).count()===0,'미지원 감정 드롭다운 없음')
 await win.getByRole('button',{name:'말하기 속도 초기화',exact:true}).click()
 check(await win.getByRole('slider',{name:'말하기 속도'}).inputValue()==='1','속도 개별 초기화')
 await win.getByRole('slider',{name:'말하기 속도'}).fill('1.2')
 await win.getByRole('button',{name:'취소',exact:true}).click()
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[0].settings.speed)===1,'옵션 취소는 기존 설정 보존')
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 await win.getByRole('slider',{name:'말하기 속도'}).fill('1.15')
 await win.getByTestId('card-reference-settings').locator('summary').click()
 await win.getByRole('combobox',{name:'참조 구간 방식'}).selectOption('manual')
 await win.getByRole('spinbutton',{name:'참조 시작 초'}).fill('2')
 await win.getByRole('spinbutton',{name:'참조 끝 초'}).fill('1')
 check(await win.getByRole('button',{name:'적용',exact:true}).isDisabled(),'역전된 참조 구간 적용 차단')
 await win.getByRole('spinbutton',{name:'참조 끝 초'}).fill('6')
 await capture('02-settings')
 await win.getByRole('button',{name:'적용',exact:true}).click()
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[0].settings.speed)===1.15,'카드별 설정 적용')
 await win.getByRole('button',{name:'1번 카드 복제',exact:true}).click()
 check(await win.getByTestId('generation-card').count()===2,'카드 복제')
 check(await win.getByTestId('card-script').nth(1).inputValue()==='','복제 시 대사·생성본 비움')
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[1].settings.speed)===1.15,'복제 시 목소리와 설정 이어받음')
 await win.getByRole('textbox',{name:'2번 카드 이름'}).fill('목소리 B')
 await win.getByTestId('card-script').nth(1).fill('좋아요. 이 목소리로 다음 대사를 이어갈게요.')
 await app.evaluate(({ipcMain},p)=>{ipcMain.removeHandler('audio:select-file');ipcMain.handle('audio:select-file',()=>p)},other)
 // 목소리 바꾸기는 이제 갈래를 먼저 고른다(기본 목소리 / 파일). 검증 의도는 그대로다.
 await win.getByRole('button',{name:'2번 카드 목소리 변경'}).click()
 await win.getByTestId('voice-source-reference').click()      // 새 고르기: 내 목소리 파일 탭
 await win.getByTestId('pick-voice-file').click()
 await win.waitForFunction(p=>window.__synthesisCards.getState().cards[1].source.path===p,other)
 check(await win.evaluate(p=>window.__afStore.getState().fileInfo.path===p&&window.__synthesisCards.getState().cards[0].source.path===p,src),'개별 음원 변경은 공통 원본·다른 카드에 영향 없음')
 await win.getByTestId('card-reference-retry').first().waitFor()
 const retryBefore=await app.evaluate(()=>globalThis.__cardTrimCalls)
 const otherRef=await win.evaluate(()=>{const s=window.__synthesisCards.getState();return s.refs[s.cards[1].id]?.reqId})
 await win.getByTestId('card-reference-retry').first().click()
 await win.waitForFunction(()=>{const s=window.__synthesisCards.getState();return s.refs[s.cards[0].id]?.phase==='failed'})
 check(await app.evaluate(()=>globalThis.__cardTrimCalls)===retryBefore+1,'재시도 한 번에 해당 참조 준비를 한 번만 요청')
 check(await win.evaluate(id=>{const s=window.__synthesisCards.getState();return s.refs[s.cards[1].id]?.reqId===id},otherRef),'다시 시도는 다른 카드의 준비 상태를 바꾸지 않음')
 const ids=await win.evaluate(()=>window.__synthesisCards.getState().cards.map(c=>c.id))
 await win.getByTestId('card-drag-handle').nth(1).focus();await win.keyboard.press('Alt+ArrowUp')
 check(await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[1]),'키보드 카드 순서 변경')
 await win.getByTestId('card-drag-handle').first().focus();await win.keyboard.press('Alt+ArrowDown')
 // ★재정렬 애니메이션이 **멈춘 뒤** 사람처럼 마우스로 끈다(2026-10-03) — 움직이는 중의 자리로 굴리면 끝난 뒤 손잡이가 굴림 칸 밖으로 숨는다.
 //   놓는 자리는 '다음 카드의 아래 절반'(뒤로 놓기)·'앞 카드의 위 절반'(앞으로 놓기) 중 **보이는 곳**. 안 보이면 굴림 칸 끝에 머물러 저절로 굴러가게 한다.
 const settleAnim=()=>win.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))))
 const snapshotCards=()=>win.evaluate(()=>window.__synthesisCards.getState().cards.map(c=>JSON.stringify({id:c.id,label:c.label,script:c.script,source:c.source,settings:c.settings,takes:c.takes,adopted:c.adopted??null})))
 const domOrder=()=>win.evaluate(()=>[...document.querySelectorAll('[data-testid="generation-card"]')].map(e=>e.getAttribute('data-card-id')))
 const dragCard=async(fromIdx,toIdx,{after,prescroll})=>{
  await settleAnim()
  const content=win.getByTestId('workspace-content')
  // 손잡이가 굴림 칸 안에 오게 — 위쪽 정렬(prescroll:'top') 또는 맨 아래까지 굴린 상태(prescroll:'bottom')에서 시작한다.
  await content.evaluate((el,a)=>{const h=el.querySelectorAll('[data-testid="card-drag-handle"]')[a.from];if(a.prescroll==='bottom'){el.scrollTop=el.scrollHeight}else{el.scrollTop+=h.getBoundingClientRect().top-el.getBoundingClientRect().top-24}
   const r=h.getBoundingClientRect(),c=el.getBoundingClientRect();if(r.top<c.top||r.bottom>c.bottom)h.scrollIntoView({block:'nearest'})},{from:fromIdx,prescroll})
  await settleAnim()
  const startTop=await content.evaluate(el=>el.scrollTop)
  const hb=await win.getByTestId('card-drag-handle').nth(fromIdx).boundingBox()
  await win.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2);await win.mouse.down();await win.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2+(after?12:-12),{steps:3})
  let dropped=false
  for(let i=0;i<80&&!dropped;i++){
   const g=await content.evaluate((el,a)=>{const c=el.getBoundingClientRect(),r=el.querySelectorAll('[data-testid="generation-card"]')[a.to].getBoundingClientRect(),mid=r.top+r.height/2
    const lo=a.after?Math.max(mid+6,c.top+6):Math.max(r.top+6,c.top+6),hi=a.after?Math.min(r.bottom-6,c.bottom-6):Math.min(mid-6,c.bottom-6)
    return {x:r.left+100,lo,hi,edge:a.after?c.bottom-4:c.top+4}},{to:toIdx,after})
   if(g.hi-g.lo>=8){await win.mouse.move(g.x,(g.lo+g.hi)/2,{steps:8});await win.mouse.up();dropped=true}
   else{await win.mouse.move(g.x,g.edge,{steps:2});await win.waitForTimeout(60)}
  }
  if(!dropped)await win.mouse.up()
  await settleAnim()
  return {dropped,scrolled:startTop!==await content.evaluate(el=>el.scrollTop)}
 }
 const before=await snapshotCards()
 const d1=await dragCard(0,1,{after:true,prescroll:'top'})
 check(d1.dropped&&await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[1]),'손잡이 드래그로 카드 묶음 이동')
 // ★화면의 카드 순서 = 저장된 순서 = 최종 연결 순서(연결 계획은 저장된 순서로 만든다 — SynthesisCardWorkspace buildJoinPlan(cards.map…)).
 check(JSON.stringify(await domOrder())===JSON.stringify(await win.evaluate(()=>window.__synthesisCards.getState().cards.map(c=>c.id))),'화면 카드 순서와 연결 순서가 같다')
 const after1=await snapshotCards()
 check(JSON.stringify([...before].sort())===JSON.stringify([...after1].sort()),'끌어 옮겨도 카드 대사·목소리·생성본·채택이 그대로다')
 // 맨 아래까지 굴린 상태에서 아래 카드를 앞으로 — 앞 카드가 칸 위로 숨어 있으면 칸 끝에 머물러 굴러가게 한다.
 const d2=await dragCard(1,0,{after:false,prescroll:'bottom'})
 check(d2.dropped&&await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[0]),'목록을 끝까지 굴린 뒤에도 손잡이로 앞으로 옮긴다')
 check(JSON.stringify(await domOrder())===JSON.stringify(await win.evaluate(()=>window.__synthesisCards.getState().cards.map(c=>c.id))),'굴린 뒤 옮겨도 화면 순서 = 연결 순서')
 // 좁은 창 — 같은 조작이 된다(카드가 길어져 굴림이 더 필요하다).
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(760,700));await win.waitForTimeout(300)
 const d3=await dragCard(0,1,{after:true,prescroll:'top'})
 check(d3.dropped&&await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[1]),'좁은 창에서도 손잡이 드래그로 옮긴다')
 const d4=await dragCard(1,0,{after:false,prescroll:'bottom'})
 check(d4.dropped&&await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[0]),'좁은 창에서 굴린 뒤에도 앞으로 옮긴다')
 check(JSON.stringify([...before].sort())===JSON.stringify([...await snapshotCards()].sort()),'여러 번 옮겨도 카드 내용이 그대로다')
 console.log('INFO 드래그 중 저절로 굴렀나',JSON.stringify({넓은창_뒤로:d1.scrolled,넓은창_앞으로:d2.scrolled,좁은창_뒤로:d3.scrolled,좁은창_앞으로:d4.scrolled}))
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1280,850));await win.waitForTimeout(300)
 // 뒤 검사는 카드 1이 앞(ids[1] 먼저)인 상태를 기대한다 — 예전 흐름의 끝 상태로 되돌린다.
 await dragCard(0,1,{after:true,prescroll:'top'})
 check(await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[1]),'(뒤 검사용 순서로 되돌림)')
 await win.getByTestId('card-drag-handle').first().focus();await win.keyboard.press('Alt+ArrowDown')
 await win.getByRole('button',{name:'2번 카드 삭제'}).click();await win.getByRole('button',{name:'되돌리기',exact:true}).click()
 check(await win.evaluate(id=>window.__synthesisCards.getState().cards[1].id===id,ids[1]),'삭제 취소로 카드와 순서 복구')
 // 모델 결과가 아닌 명시적인 테스트 fixture. 실제 WAV 재생과 스냅샷 표시만 검증한다.
 await win.evaluate(p=>{const s=window.__synthesisCards.getState(),c=s.cards[0];s.update(c.id,{takes:[1,2,3].map(i=>({id:'take-'+i,path:p,createdAt:Date.now()+i*1000,text:'생성 당시의 대사 '+i,source:{...c.source},settings:{...c.settings},applied:{speed:c.settings.speed,pitch:c.settings.pitch,notes:[]}})),adoptedId:'take-1'})},src)
 await win.getByTestId('card-takes').first().click()
 check(await win.getByRole('button',{name:/파일 위치$/}).count()===3,'생성 순서대로 간결한 목록 표시')
 await win.getByRole('button',{name:'생성본 2 대사 보기'}).click()
 check(await win.getByRole('button',{name:'생성본 2 대사 보기'}).getAttribute('aria-expanded')==='true','대사 펼침 상태를 키보드·보조기기에 전달')
 check((await win.getByRole('dialog',{name:'생성본',exact:true}).textContent()).includes('생성 당시의 대사 2'),'생성 당시 대사 확인')
 await win.getByRole('button',{name:'생성본 2 채택'}).click()
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[0].adoptedId)==='take-2','목록에서 채택 변경')
 await win.getByRole('button',{name:'생성본 2 재생'}).click();await win.getByRole('button',{name:'생성본 2 정지'}).waitFor()
 check(await win.getByRole('button',{name:'생성본 2 정지'}).locator('svg rect').count()===1,'재생 중 정지 아이콘으로 변경')
 check(await win.locator('[data-testid="take-row"][data-playing="true"]').count()===1,'재생 중인 생성본 한 개만 강조')
 await capture('03-takes-playing')
 await win.getByRole('button',{name:'생성본 2 정지'}).click()
 check(await win.locator('[data-testid="take-row"][data-playing="true"]').count()===0,'정지 후 재생 표시 해제')
 await capture('03-takes')
 await win.keyboard.press('Escape')
 check(await win.getByRole('dialog').count()===0,'Escape로 팝업 닫기')
 await win.getByTestId('join-sequence').click()
 const sequence=win.getByRole('dialog',{name:'최종 음성 구성',exact:true})
 check(await sequence.getByTestId('join-sequence-row').count()===2,'최종 음성 구성에 카드 순서·채택 표시')
 check((await sequence.getByTestId('join-sequence-row').nth(1).textContent()).includes('채택 필요'),'미채택 카드를 구분')
 await capture('06-sequence')
 await sequence.getByRole('button',{name:'2번 카드 카드로 이동'}).click()
 check(await win.getByTestId('card-script').nth(1).evaluate(el=>el===document.activeElement),'미생성 카드로 이동하면 대사에 초점')
 await win.getByTestId('join-sequence').click()
 await win.getByRole('button',{name:'1번 카드 생성본 선택'}).click()
 check(await win.getByRole('dialog',{name:'생성본',exact:true}).count()===1,'구성 목록에서 해당 카드 생성본으로 이동')
 await win.getByRole('button',{name:'생성본 3 채택',exact:true}).click()
 await win.getByRole('button',{name:'최종 음성 구성으로 돌아가기'}).click()
 check((await win.getByTestId('join-sequence-row').first().textContent()).includes('생성본 03 채택'),'채택 변경 후 최종 구성으로 돌아와 같은 결과 확인')
 await win.getByRole('button',{name:'1번 카드 생성본 선택'}).click()
 await win.getByRole('button',{name:'생성본 2 채택',exact:true}).click()
 await win.getByRole('button',{name:'최종 음성 구성으로 돌아가기'}).click()
 await win.keyboard.press('Escape')
 await win.evaluate(()=>{const s=window.__synthesisCards.getState(),c=s.cards[0];s.update(c.id,{takes:c.takes.map(t=>t.id===c.adoptedId?{...t,missing:true}:t)})})
 check((await win.getByTestId('join-sequence').textContent()).includes('0 / 2'),'파일 없는 채택본을 준비 개수에 포함하지 않음')
 await win.getByTestId('join-sequence').click()
 check((await win.getByTestId('join-sequence-row').first().textContent()).includes('파일 확인 필요'),'파일 유실은 미채택과 구분')
 await win.keyboard.press('Escape')
 await win.evaluate(()=>{const s=window.__synthesisCards.getState(),c=s.cards[0];s.update(c.id,{takes:c.takes.map(t=>({...t,missing:false}))})})
 await win.getByRole('button',{name:'연결 조정',exact:true}).click()
 check(!(await win.getByRole('checkbox',{name:'음량 맞추기'}).locator('..').getAttribute('title')).includes('구현 후'),'연결된 기능에 미구현 안내가 남지 않음')
 await win.getByRole('spinbutton',{name:'1번과 2번 카드 간격'}).fill('.65')
 await capture('04-join')
 await win.getByRole('button',{name:'적용',exact:true}).click()
 check(await win.evaluate(()=>Object.values(window.__synthesisCards.getState().joins.gaps)[0])===.65,'카드 외부의 개별 연결 간격 저장')
 // 생성은 이제 연결되어 있다. 여기서 잠긴 이유는 '미연결' 이 아니라 **참조 구간 미확정**이다
 // (이 검사는 audio:analyze-reference 를 needs_region 으로 세워 둔다). 조건이 없으면 못 만든다.
 check(await win.getByTestId('card-generate').first().isDisabled(),'조건 미충족 시 생성 차단(참조 구간 미확정)')
 check(await win.getByRole('button',{name:'파일로 저장',exact:true}).isDisabled(),'연결 전 가짜 출력 차단')
 await win.getByTestId('mode-music').click();await win.getByTestId('mode-tts').click()
 check(await win.getByTestId('generation-card').count()===2,'메뉴 왕복 시 현재 실행의 카드 보존')
 await win.getByTestId('workspace-content').evaluate(el=>el.scrollTop=0)
 await capture('01-cards')
 await win.getByTestId('open-legacy-synthesis').click();await win.getByTestId('synthesis-tabs').waitFor()
 check(await win.getByTestId('synthesis-tab-basic').count()===1,'기존 제작 기능 접근 보존')
 await win.getByTestId('back-to-generation-cards').click()
 check(await win.getByTestId('generation-card').count()===2,'기존 작업 왕복 후 새 카드 보존')
 await win.getByTestId('back-to-generation-cards').focus();await win.keyboard.press('ArrowRight')
 check(await win.getByTestId('open-legacy-synthesis').getAttribute('aria-selected')==='true'&&await win.getByTestId('open-legacy-synthesis').evaluate(el=>el===document.activeElement),'버전 탭 방향키는 선택과 초점을 함께 이동')
 await win.keyboard.press('Home')
 check(await win.getByTestId('back-to-generation-cards').getAttribute('tabindex')==='0'&&await win.getByTestId('open-legacy-synthesis').getAttribute('tabindex')==='-1','선택된 버전 탭만 Tab 순서에 포함')
 check(await win.locator('#synthesis-version-panel-cards').getAttribute('aria-labelledby')==='synthesis-version-cards','버전 탭과 작업 화면의 접근성 연결')
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(800,720))
 await win.getByTestId('workspace-content').evaluate(el=>el.scrollTop=0)
 check(await win.getByTestId('workspace-content').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'800px 창에서 가로 넘침 없음')
 await capture('05-narrow')
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 check(await win.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'800px 팝업 가로 넘침 없음')
 await win.keyboard.press('Escape')
 // BrowserWindow zoom shrinks the CSS viewport; header and footer must remain reachable.
 await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(800,600);w.webContents.setZoomFactor(1.5)})
 await win.getByTestId('card-takes').first().click()
 await win.getByRole('button',{name:'생성본 2 대사 보기'}).click()
 const bounds=await win.getByRole('dialog').evaluate(el=>{const r=el.getBoundingClientRect();const close=el.querySelector('button[aria-label="팝업 닫기"]').getBoundingClientRect();const foot=el.lastElementChild.getBoundingClientRect();return {fits:r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1,close:close.top>=0&&close.bottom<=innerHeight,footer:foot.top>=0&&foot.bottom<=innerHeight,wide:el.scrollWidth<=el.clientWidth+1}})
 check(bounds.fits&&bounds.close&&bounds.footer&&bounds.wide,'800×600·150% 확대에서도 팝업·닫기·하단 버튼이 화면 안에 유지')
 await capture('07-zoom-takes')
 await win.keyboard.press('Escape')
 await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.webContents.setZoomFactor(1);w.setSize(800,720)})
 await win.emulateMedia({reducedMotion:'reduce'})
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 check(await win.getByRole('dialog').evaluate(el=>getComputedStyle(el).animationName)==='none','모션 감소 시 팝업 모션 생략')
 await win.keyboard.press('Escape')
 await win.getByTestId('card-drag-handle').nth(1).focus();await win.keyboard.press('Alt+ArrowUp')
 check(await win.getByTestId('generation-card').evaluateAll(els=>els.every(el=>el.getAnimations().length===0)),'모션 감소 시 카드 이동 애니메이션 생략')
 await win.keyboard.press('Alt+ArrowDown')
 // A built-in change has no source path difference; old takes still need a stale marker.
 await win.evaluate(()=>{
   const s=window.__synthesisCards.getState(),c=s.cards[0];
   const voice={engineId:'piper',modelId:'old-fixture',path:'old.onnx',label:'기본 목소리',language:'ko',sampleRate:22050};
   s.setBuiltin(c.id,voice);
   const updated=window.__synthesisCards.getState().cards[0];
   s.update(c.id,{takes:[{id:'builtin-take',path:c.takes[0].path,text:updated.text,createdAt:Date.now(),source:{path:'',name:voice.label,duration:0},settings:{...updated.settings},applied:{speed:1,pitch:0,notes:[]},voice:{kind:'builtin',label:voice.label,engineId:voice.engineId,modelId:voice.modelId,language:'ko'}}],adoptedId:'builtin-take'});
   s.setBuiltin(c.id,{...voice,modelId:'new-fixture',path:'new.onnx'});
 })
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 check(await win.getByTestId('card-reference-settings').count()===0,'기본 목소리 옵션에 불필요한 참조 구간 없음')
 check(!(await win.getByRole('dialog').textContent()).includes('감정 참조'),'기본 설정에 미연결 감정 패널 없음')
 await win.keyboard.press('Escape')
 check((await win.getByTestId('generation-card').first().textContent()).includes('수정 전'),'기본 목소리 교체 후 이전 채택본에 수정 전 표시')
 await win.getByTestId('card-takes').first().click()
 check((await win.getByTestId('take-row').first().textContent()).includes('수정 전'),'생성본 목록도 기본 목소리 변경을 같은 기준으로 표시')
 await win.keyboard.press('Escape')
 await win.getByTestId('join-sequence').click()
 check((await win.getByTestId('join-sequence-row').first().textContent()).includes('수정 전'),'최종 음성 구성에서도 수정 전 채택본을 알림')
 await win.keyboard.press('Escape')
 await win.evaluate(()=>window.__afStore.setState({status:'processing'}))
 check(await win.getByTestId('add-generation-card').isDisabled()&&await win.getByTestId('card-script').first().isDisabled(),'실제 작업 중 카드 변경 잠금')
 await win.getByTestId('back-to-generation-cards').focus();await win.keyboard.press('End')
 check(await win.getByTestId('back-to-generation-cards').getAttribute('aria-selected')==='true','작업 중 키보드로 버전 전환 잠금을 우회하지 않음')
 await win.evaluate(()=>window.__afStore.setState({status:'idle'}))
 check(await app.evaluate(()=>globalThis.__cardCalls)===0,'음성 생성 IPC 0회')
 check(errors.length===0,'페이지 예외 없음: '+errors.join(','))
 console.log('RESULT',passed,'checks',shots)
}catch(e){console.error(e);if(win)await capture('failure').catch(()=>{});console.error('SHOTS',shots,'ERRORS',errors);process.exitCode=1}
finally{if(app)await app.close();if(!process.exitCode)cleanupUserData(ud)}
