import { _electron as electron } from 'playwright'
import fs from 'fs'
import path from 'path'
import os from 'os'
import { isolatedUserData, cleanupUserData, makeSyntheticWav } from './_e2e-helper.mjs'
const root=process.cwd(),ud=isolatedUserData(),src=makeSyntheticWav(path.join(ud,'reference-a.wav'),8),other=makeSyntheticWav(path.join(ud,'reference-b.wav'),7,24000,220)
const shots=fs.mkdtempSync(path.join(os.tmpdir(),'af-unified-cards-shots-'))
let app,win,passed=0;const errors=[]
const capture=async name=>{await win.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await win.screenshot({path:path.join(shots,name+'.png')})};
const check=(v,label)=>{if(!v)throw Error(label);passed++;console.log('PASS',label)}
try{
 app=await electron.launch({args:['out/main/index.js'],cwd:root,env:{...process.env,AF_E2E:'1',AF_E2E_USER_DATA:ud,AUDIOFORGE_NO_WARMUP:'1',HF_HUB_OFFLINE:'1',AF_E2E_SELECT_FILE:src}})
 win=await app.firstWindow();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1280,850));win.setDefaultTimeout(10000);win.on('pageerror',e=>errors.push(e.message))
 await win.waitForFunction(()=>!!window.__afStore&&!!window.__synthesisCards)
 await app.evaluate(({ipcMain},src)=>{
  const replace=(c,f)=>{ipcMain.removeHandler(c);ipcMain.handle(c,f)}
  globalThis.__cardCalls=0
  replace('audio:select-file',()=>src)
  replace('audio:get-file-info',(_e,p)=>({path:p,name:p.split(/[/\\]/).pop(),duration:8,sampleRate:24000,channels:1,format:'wav'}))
  replace('card:extract-audio',(_e,_id,p)=>({ok:true,data:p}))
  replace('audio:trim-reference',()=>({error:'GUI 검사: 구간 미확정'}))
  replace('audio:process',()=>{globalThis.__cardCalls++;throw Error('GUI-only should not synthesize')})
  replace('analysis:prewarm',()=>({ready:false}))
  replace('analysis:analyze',(_e,req)=>({ok:false,requestId:req.requestId,code:'WORKER_UNAVAILABLE',reason:'GUI check'}))
  replace('audio:analyze-reference',()=>({valid_whole:false,too_short:false,needs_region:true,duration_sec:8,sample_rate:24000,channels:1,policy:{engine:'qwen3',required:{min_sec:1,max_sec:null},recommended:{min_sec:3,max_sec:5}},recommend:{ok:false}}))
 },src)
 await win.getByTestId('mode-tts').click()
 await win.getByTestId('synthesis-card-workspace').waitFor()
 check(await win.getByTestId('synthesis-tabs').count()===0,'통합 화면에 제작 방식 탭 없음')
 check(await win.getByTestId('generation-card').count()===0,'초기에는 파일 없는 카드도 없음')
 await win.evaluate(p=>window.__afStore.setState({fileInfo:{path:p,name:'목소리 A.wav',duration:8,channels:1,sampleRate:24000,format:'wav'}}),src)
 await win.getByTestId('generation-card').waitFor()
 await win.waitForFunction(()=>document.querySelector('[data-testid="compact-voice-wave"]')?.dataset.state==='ready')
 check(await win.getByTestId('generation-card').count()===1,'공통 원본으로 첫 카드 자동 구성')
 await win.getByTestId('card-script').fill('안녕하세요. 오늘은 함께 이야기를 만들어 볼까요?')
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 await win.getByRole('dialog',{name:'고급 옵션'}).waitFor()
 check(await win.locator('dialog').evaluate(el=>el.contains(document.activeElement)),'팝업 내부로 키보드 초점 이동')
 await win.getByRole('slider',{name:'말하기 속도'}).fill('1.2')
 check(await win.getByRole('slider',{name:'음높이'}).getAttribute('max')==='2'&&await win.getByRole('slider',{name:'음높이'}).getAttribute('step')==='0.5','음높이 엔진 범위와 일치')
 check(await win.getByRole('combobox',{name:'감정',exact:true}).count()===0,'미지원 감정 드롭다운 없음')
 await win.getByRole('button',{name:'말하기 속도 초기화',exact:true}).click()
 check(await win.getByRole('slider',{name:'말하기 속도'}).inputValue()==='1','속도 개별 초기화')
 await win.getByRole('slider',{name:'말하기 속도'}).fill('1.2')
 await win.getByRole('button',{name:'취소',exact:true}).click()
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[0].settings.speed)===1,'옵션 취소는 기존 설정 보존')
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 await win.getByRole('slider',{name:'말하기 속도'}).fill('1.15')
 await win.getByTestId('card-reference-settings').locator('summary').click()
 await win.getByRole('combobox',{name:'참조 구간 방식'}).selectOption('manual')
 await win.getByRole('spinbutton',{name:'참조 시작 초'}).fill('2')
 await win.getByRole('spinbutton',{name:'참조 끝 초'}).fill('1')
 check(await win.getByRole('button',{name:'적용',exact:true}).isDisabled(),'역전된 참조 구간 적용 차단')
 await win.getByRole('spinbutton',{name:'참조 끝 초'}).fill('6')
 await capture('02-settings')
 await win.getByRole('button',{name:'적용',exact:true}).click()
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[0].settings.speed)===1.15,'카드별 설정 적용')
 await win.getByRole('button',{name:'1번 카드 복제',exact:true}).click()
 check(await win.getByTestId('generation-card').count()===2,'카드 복제')
 check(await win.getByTestId('card-script').nth(1).inputValue()==='','복제 시 대사·생성본 비움')
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[1].settings.speed)===1.15,'복제 시 목소리와 설정 이어받음')
 await win.getByRole('textbox',{name:'2번 카드 이름'}).fill('목소리 B')
 await win.getByTestId('card-script').nth(1).fill('좋아요. 이 목소리로 다음 대사를 이어갈게요.')
 await app.evaluate(({ipcMain},p)=>{ipcMain.removeHandler('audio:select-file');ipcMain.handle('audio:select-file',()=>p)},other)
 await win.getByRole('button',{name:'2번 카드 음원 변경'}).click()
 await win.waitForFunction(p=>window.__synthesisCards.getState().cards[1].source.path===p,other)
 check(await win.evaluate(p=>window.__afStore.getState().fileInfo.path===p&&window.__synthesisCards.getState().cards[0].source.path===p,src),'개별 음원 변경은 공통 원본·다른 카드에 영향 없음')
 const ids=await win.evaluate(()=>window.__synthesisCards.getState().cards.map(c=>c.id))
 await win.getByTestId('card-drag-handle').nth(1).focus();await win.keyboard.press('Alt+ArrowUp')
 check(await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[1]),'키보드 카드 순서 변경')
 await win.getByTestId('card-drag-handle').first().focus();await win.keyboard.press('Alt+ArrowDown')
 // Keep source and target visible together; dragTo scrolling its target otherwise displaces the source.
 await win.getByTestId('workspace-content').evaluate(el=>{const card=el.querySelector('[data-testid="generation-card"]');el.scrollTop+=card.getBoundingClientRect().top-el.getBoundingClientRect().top-16})
 const dropBox=await win.getByTestId('generation-card').nth(1).boundingBox()
 await win.getByTestId('card-drag-handle').first().dragTo(win.getByTestId('generation-card').nth(1),{targetPosition:{x:100,y:dropBox.height-8}})
 check(await win.evaluate(id=>window.__synthesisCards.getState().cards[0].id===id,ids[1]),'손잡이 드래그로 카드 묶음 이동')
 await win.getByTestId('card-drag-handle').first().focus();await win.keyboard.press('Alt+ArrowDown')
 await win.getByRole('button',{name:'2번 카드 삭제'}).click();await win.getByRole('button',{name:'되돌리기',exact:true}).click()
 check(await win.evaluate(id=>window.__synthesisCards.getState().cards[1].id===id,ids[1]),'삭제 취소로 카드와 순서 복구')
 // 모델 결과가 아닌 명시적인 테스트 fixture. 실제 WAV 재생과 스냅샷 표시만 검증한다.
 await win.evaluate(p=>{const s=window.__synthesisCards.getState(),c=s.cards[0];s.update(c.id,{takes:[1,2,3].map(i=>({id:'take-'+i,path:p,createdAt:Date.now()+i*1000,text:'생성 당시의 대사 '+i,source:{...c.source},settings:{...c.settings},applied:{speed:c.settings.speed,pitch:c.settings.pitch,notes:[]}})),adoptedId:'take-1'})},src)
 await win.getByTestId('card-takes').first().click()
 check(await win.getByRole('button',{name:/파일 위치$/}).count()===3,'생성 순서대로 간결한 목록 표시')
 await win.getByRole('button',{name:'생성본 2 대사 보기'}).click()
 check((await win.getByRole('dialog',{name:'생성본',exact:true}).textContent()).includes('생성 당시의 대사 2'),'생성 당시 대사 확인')
 await win.getByRole('button',{name:'생성본 2 채택'}).click()
 check(await win.evaluate(()=>window.__synthesisCards.getState().cards[0].adoptedId)==='take-2','목록에서 채택 변경')
 await win.getByRole('button',{name:'생성본 2 재생'}).click();await win.getByRole('button',{name:'생성본 2 정지'}).waitFor()
 await win.getByRole('button',{name:'생성본 2 정지'}).click()
 await capture('03-takes')
 await win.keyboard.press('Escape')
 check(await win.getByRole('dialog').count()===0,'Escape로 팝업 닫기')
 await win.getByRole('button',{name:'연결 조정',exact:true}).click()
 await win.getByRole('spinbutton',{name:'1번과 2번 카드 간격'}).fill('.65')
 await capture('04-join')
 await win.getByRole('button',{name:'적용',exact:true}).click()
 check(await win.evaluate(()=>Object.values(window.__synthesisCards.getState().joins.gaps)[0])===.65,'카드 외부의 개별 연결 간격 저장')
 // 생성은 이제 연결되어 있다. 여기서 잠긴 이유는 '미연결' 이 아니라 **참조 구간 미확정**이다
 // (이 검사는 audio:analyze-reference 를 needs_region 으로 세워 둔다). 조건이 없으면 못 만든다.
 check(await win.getByTestId('card-generate').first().isDisabled(),'조건 미충족 시 생성 차단(참조 구간 미확정)')
 check(await win.getByRole('button',{name:'파일로 저장',exact:true}).isDisabled(),'연결 전 가짜 출력 차단')
 await win.getByTestId('mode-music').click();await win.getByTestId('mode-tts').click()
 check(await win.getByTestId('generation-card').count()===2,'메뉴 왕복 시 현재 실행의 카드 보존')
 await win.getByTestId('workspace-content').evaluate(el=>el.scrollTop=0)
 await capture('01-cards')
 await win.getByTestId('open-legacy-synthesis').click();await win.getByTestId('synthesis-tabs').waitFor()
 check(await win.getByTestId('synthesis-tab-basic').count()===1,'기존 제작 기능 접근 보존')
 await win.getByTestId('back-to-generation-cards').click()
 check(await win.getByTestId('generation-card').count()===2,'기존 작업 왕복 후 새 카드 보존')
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(800,720))
 await win.getByTestId('workspace-content').evaluate(el=>el.scrollTop=0)
 check(await win.getByTestId('workspace-content').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'800px 창에서 가로 넘침 없음')
 await capture('05-narrow')
 await win.getByRole('button',{name:'1번 카드 고급 옵션',exact:true}).click()
 check(await win.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'800px 팝업 가로 넘침 없음')
 await win.keyboard.press('Escape')
 await win.evaluate(()=>window.__afStore.setState({status:'processing'}))
 check(await win.getByTestId('add-generation-card').isDisabled()&&await win.getByTestId('card-script').first().isDisabled(),'실제 작업 중 카드 변경 잠금')
 await win.evaluate(()=>window.__afStore.setState({status:'idle'}))
 check(await app.evaluate(()=>globalThis.__cardCalls)===0,'음성 생성 IPC 0회')
 check(errors.length===0,'페이지 예외 없음: '+errors.join(','))
 console.log('RESULT',passed,'checks',shots)
}catch(e){console.error(e);if(win)await capture('failure').catch(()=>{});console.error('SHOTS',shots,'ERRORS',errors);process.exitCode=1}
finally{if(app)await app.close();if(!process.exitCode)cleanupUserData(ud)}
